name: build image
on: [push]
jobs:
  build-image:
    name: Build image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the docker image
        run: |
          docker build . --tag ghcr.io/mos-wannit/my-learning:latest
      - name: Push the docker image
        run: docker push ghcr.io/mos-wannit/my-learning:latest